name: Main Workflow

on:
  push:
    tags:
      - "*"

jobs:
  run-linux:
    uses: ./.github/workflows/appimage.yml

  run-windows:
    needs: run-linux
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  publish:
    needs: [run-linux, run-windows]
    uses: ./.github/workflows/artifacts.yml
